
name: dataplicity-agent
version: git
summary: Dataplicity Agent
description: |
  Dataplicity Agent is a service which enables remote terminals and web
  forwarding from Dataplicity.com
grade: devel
confinement: devmode

apps:
  dataplicity-agent:
    command: bin/dataplicity --log-file /var/log/dataplicity.log run
    daemon: simple

  dataplicity:
    command: bin/dataplicity

parts:
  dataplicity:
    plugin: python
    python-version: python2
    requirements: requirements.txt
    source: .

