
name: dataplicity-agent
version: git
summary: Dataplicity Agent
description: |
  Dataplicity Agent is a service which enables remote terminals and web
  forwarding from Dataplicity.com
grade: devel
confinement: devmode

apps:
  dataplicity-agent:
    command : bin/dataplicity --log-level debug --auth 237FBqeREy3Obielp5du --serial 09a0332a-e9e8-4d87-abbd-89866fa65750 --m2m-url wss://m2m.dptestenv.com/m2m/ --server-url https://api.dptestenv.com run
    daemon: simple

  dataplicity:
    command: bin/dataplicity

parts:
  dataplicity:
    plugin: python
    python-version: python2
    requirements: requirements.txt
    source: .

